feat: Switch polygon tool pattern / feat: Show key point
open-mmlab/labelbee pull request #242
Opened 2023-07-11 07:16 UTC by Asliuyong

2023-07-14 07:56 UTC, Glenfiddish commented on packages/lb-annotation/src/core/toolOperation/polygonOperation.ts
> +        this.isSingleCropping = false;
is isSingleCropping can implement in crop? Single and multiple should be handle in a function.

2023-07-14 07:57 UTC, Glenfiddish commented on packages/lb-components/src/views/MainView/sidebar/OperationRotate/index.tsx
> + * @file Rotate polygon
rotate on point cloud

2023-07-14 07:59 UTC, Glenfiddish requested changes
Reviewed

2023-07-21 06:37 UTC, Kerwin-L commented on packages/lb-components/src/views/MainView/sidebar/OperationRotate/index.tsx
> +      name: '左旋1°(←)',
Please add the shortcut key

2023-07-21 06:45 UTC, Kerwin-L commented on packages/lb-components/src/views/MainView/sidebar/ToolStyle/index.tsx
> +          (annotationConfig?.attributeConfigurable === true || annotationConfig?.lineColor) &&
Need to judge `lineColor` whether `lineColor` is `ELineColor.MultiColor`

2023-07-21 07:10 UTC, Kerwin-L commented on packages/lb-components/src/components/customResizeHook/index.tsx
> +        e.preventDefault()
If it is `Ctrl + R(Command + R)`， then do not `rotate`

2023-07-25 03:09 UTC, merged