fix: LLM tool input text display three lines / fix: LLM tool fix setValid
open-mmlab/labelbee pull request #445
Opened 2024-04-26 07:17 UTC by lixinghua123

2024-04-26 07:25 UTC, Glenfiddish commented on packages/lb-components/src/components/longText/index.tsx
> +    const isOverflowByWordCount = wordCount && text?.length > wordCount;
Variable calc should wrapper in fn, useMemo is preferred

2024-04-26 07:29 UTC, Glenfiddish requested changes

2024-04-26 07:29 UTC, Glenfiddish commented on packages/lb-components/src/components/longText/index.tsx
> +    const TextDom = (
Writing logic in hooks is not elegant and difficult to reuse. Try splitting (refactoring into components)

2024-04-28 03:33 UTC, lihqi approved these changes

2024-04-28 03:35 UTC, merged