feat: Show only selected
open-mmlab/labelbee pull request #506
Opened 2024-07-03 06:56 UTC by sharefe-demo

2024-07-05 08:37 UTC, lihqi requested changes

2024-07-05 09:34 UTC, sharefe-demo commented on packages/lb-components/src/components/pointCloudView/hooks/useTimeoutFunc.ts
> +import { useCallback, useEffect, useRef } from 'react';
1/2 已经补充
3 内部hook，这里认为用户是数字值, 并且支持ts typing功能

2024-07-05 09:37 UTC, sharefe-demo commented on packages/lb-components/src/components/pointCloudView/hooks/useWindowKeydownListener.ts
> +import { useCallback, useEffect, useMemo, useRef } from 'react';
1. 已补充
2. 这里需要支持同级的stop propagation(`e.isImmediatePropagationStopped()`)有所区别，用原生简化（无需支持复杂组件）流程，另外此组件是独立于任何依赖库。

2024-07-09 08:20 UTC, lihqi approved these changes

2024-07-09 08:20 UTC, merged